---
layout: page
title: xwMOOC 모형
subtitle: "고객이탈 - RESTful API 기본기 `plumber`"
author:
    name: xwMOOC
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

```


# 고객이탈 예측모형 [^telco-susan] {#predictive-model-churn}

[^telco-susan]: [Susan Li (Nov 16, 2017 ), "Predict Customer Churn with R", Towards Data Science](https://towardsdatascience.com/predict-customer-churn-with-r-9e62357d47b4)

## 데이터 전처리 {#predictive-model-preprocess}

```{r telco-glm-api}
library(tidyverse)   

telco <- read_csv("data/WA_Fn-UseC_-Telco-Customer-Churn.csv")

## 범주형 변수
cat_variables <- names(telco[9:14])

telco_df <- telco%>%
  select(-customerID, -TotalCharges) %>% 
  drop_na() %>% 
  mutate_at(.vars = cat_variables,
            .funs = ~recode_factor(., `No internet service`="No")) %>%
  mutate_at(.vars = "MultipleLines",
            .funs = ~recode_factor(., `No phone service`="No")) %>% 
  mutate(tenure = case_when(tenure >= 0 & tenure <= 12 ~ '0-12 Month',
                            tenure > 12 & tenure <= 24 ~ '12-24 Month',
                            tenure > 24 & tenure <= 48 ~ '24-48 Month',
                            tenure > 48 & tenure <= 60~ '48-60 Month', 
                            tenure > 60 ~'> 60 Month')) %>% 
  mutate(SeniorCitizen = if_else(SeniorCitizen == 0, "No", "Yes")) %>% 
  mutate_if(is.character, as.factor)
  

telco_df %>% 
  sample_n(10) %>% 
  knitr::kable()
```

## GLM 모형 {#predictive-model-logit}


```{r glm-telco-model}
telco_full <- glm(Churn ~ ., 
                family = binomial(link="logit"),
                data = telco_df)

library(MASS)
telco_stepwise <- telco_full %>% 
  stepAIC(trace = FALSE)

print(summary(telco_full))
```


