---
layout: page
title: xwMOOC 모형
subtitle: 파이썬 + R - 고객이탈 (xgBoost)
author:
    name: xwMOOC
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---
 
``` {r, include=FALSE}
# source("tools/chunk-options.R")

knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')


```

# 데이터 캠프 고객이탈 데이터 [^dc-churn-in-python] {#datacamp-churn-dataset}

[^dc-churn-in-python]: [Avinash Navlani(August 14th, 2018), "Predicting Employee Churn in Python", Datacamp](https://www.datacamp.com/community/tutorials/predicting-employee-churn-python)

## 고객이탈 데이터 가져오기 {#datacamp-churn-dataset-import}

```{r python-churn-dataset}
# 0. 환경설정 -----
library(tidyverse)
library(skimr)
library(janitor)
library(DescTools)

# 1. 데이터 가져오기 -----
download.file("https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Employee+Churn+in+Python/HR_comma_sep.csv", destfile = "data/HR_comma_sep.csv")

data <- read_csv("data/HR_comma_sep.csv") %>% 
  clean_names()


```


## 탐색적 데이터분석  {#datacamp-churn-dataset-univariate}


```{r python-churn-eda-character}
skim_data <- skim_to_list(data)

chr_variable <- skim_data$character %>% 
  pull(variable)



Desc(data$departments, plotit = TRUE)
Desc(data$salary, plotit = TRUE)

library(GGally)

data %>% 
  sample_frac(0.1) %>% 
  ggpairs(., mapping = aes(colour = as.factor(left)))

```

