---
layout: page
title: "xwMOOC 모형 - `tidymodels`"
subtitle: "`parsnip` - 초모수(hyperparameter)"
author:
    name: xwMOOC
    url: https://www.facebook.com/groups/tidyverse/
    affiliation: Tidyverse Korea
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: yes
    toc_float: true
    highlight: tango
    code_folding: show
    number_section: true
    self_contained: true
editor_options: 
  chunk_output_type: console
---
 
``` {r, include=FALSE}
# source("tools/chunk-options.R")

knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE,
                      comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')
```

# super learner [^tidymodels-super-learner] {#tidymodels-super-learner}

[^tidymodels-super-learner]: [Alex Hayes(Apr 13, 2019), "IMPLEMENTING THE SUPER LEARNER WITH TIDYMODELS"](https://www.alexpghayes.com/blog/implementing-the-super-learner-with-tidymodels/)

`tidymodels` 체계를 구성하는 `parsnip` 팩키지를 활용하여 앙상블 모형의 또 다른 형태인 `super learner`를 구현해 보자.

# 

```{r superlearner-setup}
library(tidyverse)
library(tidymodels)
library(furrr)
library(tictoc)

hr_dat <- read_csv("data/HR_comma_sep.csv") %>% 
  janitor::clean_names()

hr_df <- hr_dat %>% 
  mutate(left = factor(left, levels=c(0,1), labels=c("stay", "left"))) %>%
  mutate(departments = factor(departments),
         work_accident = factor(work_accident))

model <-  boost_tree(mode = "classification") %>%
    set_engine("xgboost")

model

xgb_grid <- grid_random(
  learn_rate  %>% range_set(c(0.1,  0.01)), 
  tree_depth  %>% range_set(c( 3,  10)), 
  sample_size %>% range_set(c(20, 130)), 
  size = 3)

xgb_grid

spec_df <- tibble(spec = merge(model, xgb_grid)) %>% 
  mutate(model_id = row_number())

spec_df
```


```{r}
hr_recipe <- function(df) {
  recipe(left ~ ., data = df) %>%
    step_dummy(all_nominal(), -all_outcomes()) %>%
    step_center(all_numeric()) %>%
    step_scale(all_numeric()) %>%
    prep(data = df)
}

prepped <- hr_recipe(hr_df)

x <- juice(prepped, all_predictors())
y <- juice(prepped, all_outcomes())

full_fits <- spec_df %>% 
  mutate(fit = future_map(spec, fit_xy, x, y))

full_fits

```

