---
title: "합을 구하는 매우 단순한 앱"
author: "Tidyverse Korea"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
runtime: shiny
---

```{r global, include=FALSE}
library(shiny)
library(tidyverse)
library(shinydashboard)
library(tidymodels)

calculate_sum <- function(x, y) {
    res <- x + y
    return(res)
}
```

Inputs {.sidebar}
-----------------------------------------------------------------------

```{r input}

sliderInput('bill_length_mm', 'Bill Length (mm)', min=32, max=50, value=43, step=1)
sliderInput('bill_depth_mm',  'Bill Depth (mm)',  min=13, max=22, value=17, step=1)
sliderInput('flipper_length_mm', 'Flipper Length (mm)', min=170, max=235, value=200, step=1)
sliderInput('body_mass_g', 'Body Mass (g)', min=2700, max=6300, value=4200, step=100)

```

펭귄 성별을 예측하는 예측모형

Column {data-width=600}
-------------------------------------

```{r penguin-features}
library(tidyverse)
library(tidymodels)

bill_length_mm  <- reactive(as.integer(input$bill_length_mm))
bill_depth_mm  <- reactive(as.integer(input$bill_depth_mm))
flipper_length_mm  <- reactive(as.integer(input$flipper_length_mm))
body_mass_g  <- reactive(as.integer(input$body_mass_g))

# penguin_df <- tibble("species" = "Adelie",
#                   "bill_length_mm" =  39.1,
#                   "bill_depth_mm" =  18.7,
#                   "flipper_length_mm" =  181,
#                   "body_mass_g" = 3750)

```

### 성별
    
```{r predict-gender}
# random_penguin <- sample(c("Chinstrap","Gentoo", "Adelie"), size =1)
# renderText(glue::glue("- Penguin: {random_penguin}"))

penguin_predictvie_model <- read_rds("../data/penguin_predictvie_model.rds")

penguin_df <- reactive({
  tibble("species" = "Adelie",
                     "bill_length_mm" =  input$bill_length_mm,
                     "bill_depth_mm" =  input$bill_depth_mm,
                     "flipper_length_mm" =  input$flipper_length_mm,
                     "body_mass_g" = input$body_mass_g)
  })

pred_sex <- reactive({
  predict(penguin_predictvie_model, penguin_df()) %>% unlist %>% as.character
})

renderPrint(pred_sex())
```

### 성별 확률
    
```{r predict-gender-probability}
# prob_penguin <- runif(n=1, min=0.5, max=1)
# renderText(glue::glue("- Penguin Prob : {round(prob_penguin*100,2)} %"))

prob_sex <- reactive({
  predict(penguin_predictvie_model, penguin_df(), type="prob")[,1]
})

renderText(glue::glue("- Penguin Prob : {round(prob_sex()*100,2)} %"))
```

   
Column {data-width=400}
-------------------------------------
   
### Bill Length (mm)

```{r penguin-features-bill_length_mm}
renderText(glue::glue("- Bill Length (mm): {bill_length_mm()}"))
```
 
### Bill Depth (mm)
    
```{r penguin-features-bill_depth_mm}
renderText(glue::glue("- Bill Depth (mm): {bill_depth_mm()}"))
```


### Flipper Length (mm)
    
```{r penguin-features-flipper_length_mm}
renderText(glue::glue("- Bill Depth (mm): {flipper_length_mm()}"))
```

### Body Mass (g)
    
```{r penguin-features-body_mass_g}
renderText(glue::glue("- Body Mass (g): {body_mass_g()}"))
```

